export const GAMES = [
  {
    id: 1,
    url: "#",
    image: "/games/img1.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 2,
    url: "#",
    image: "/games/img2.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 3,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 4,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 5,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 6,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 7,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 8,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 9,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 10,
    url: "#",
    image: "/games/img2.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 11,
    url: "#",
    image: "/games/img1.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 12,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 13,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 14,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 15,
    url: "#",
    image: "/games/img1.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 16,
    url: "#",
    image: "/games/img2.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 17,
    url: "#",
    image: "/games/img2.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 18,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 19,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 20,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 21,
    url: "#",
    image: "/games/img1.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 22,
    url: "#",
    image: "/games/img2.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 23,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 24,
    url: "#",
    image: "/games/img2.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 25,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 26,
    url: "#",
    image: "/games/img1.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 27,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 28,
    url: "#",
    image: "/games/img3.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 29,
    url: "#",
    image: "/games/img1.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
  {
    id: 30,
    url: "#",
    image: "/games/img1.jpg",
    label: "Gates Of Olympus",
    tags: ["fast", "slots", "popular"],
  },
];
